In [1]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

# Configuration
INPUT_FILE = "master-database.csv"
RANDOM_SEED = 42

# Codabench folders
TRAIN_DIR = "codabench/app/input_data/"
REF_DIR = "codabench/app/reference_data"

# Create directories
os.makedirs(TRAIN_DIR, exist_ok=True)
os.makedirs(REF_DIR, exist_ok=True)

# Load dataset
df = pd.read_csv(INPUT_FILE)

In [2]:
df = df[['video_title', 'video_description', 'category']]

In [3]:
df

,video_title,video_description,category
0,We Tested SHOCKING Tik Tok Gadgets,"🌈BUY THE SHIRTS WE'RE WEARING with code ""COLDO...",Shopping
1,[Ludum Dare #43] The Resistance: Behind the Sc...,A game about batteries. Made in 48 hours for t...,Video Games
2,Quadruple Stacked Ham Sandwich from Final Fant...,This episode is sponsored by Squarespace. Head...,Food & Cooking
3,Recreating Maangchi's Seafood Kimchi Fried Ric...,We challenged Chris Morocco to recreate Maangc...,Food & Cooking
4,7 tech leaders who ended up in prison,"Yesterday, Sam Bankman-Fried was sentenced to ...",News
...,...,...,...
1846,the best geoguessr moments of 2022,thank you all for an amazing year. \n\nedited ...,Video Games
1847,"Strange Reviews for ""Pie"" that Doesn't Exist",There's been a strange mystery online for abou...,Digital Media
1848,World’s Most Expensive Bed,NaN,Shopping
1849,The Weirdest Divorce Ever w/ Kurtis Conner,Go to https://expressvpn.com/codyko and find o...,Lifestyle
1850,How Electricity Actually Works,This video is sponsored by Brilliant. The firs...,Education

In [4]:
# Assume last column is label
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split: 80 train / 20 temp
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_SEED, shuffle=True
)

# Split temp into validation (5%) and test (15%)
X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp, y_temp, test_size=0.75, random_state=RANDOM_SEED, shuffle=True
)

In [5]:
train = len(X_train)
valid = len(X_valid)
test = len(X_test)
print(f'Train: {train}, valid: {valid}, test: {test}. total: {train+valid+test}')

Train: 1480, valid: 92, test: 279. total: 1851

In [6]:
X_train

,video_title,video_description
244,Most annoying skill ever,NaN
1101,Levy STUNS World Champion!,➡️ Get My Chess Courses: https://www.chessly....
1265,Nothing gets past Terry Crews 👀,NaN
1244,Private Room on Canada’s Overnight Sleeper Tra...,To get a 1 year supply of immune-supporting Vi...
1253,Jew,NaN
...,...,...
1130,geoguessr pros play geoguessr but in gartic phone,we are all retiring\n\nPATREON FOR MORE:\nhttp...
1294,How I WON A Chess Tournament,➡️ BONUS CONTENT HERE: https://www.patreon.com...
860,"Cinnamon Rolls 3-Ways (Pumpkin Spice, Strawber...",Pre-Order the Basics with Babish Cookbook Now!...
1459,Watch 3 Speedrunners Play Hitman H.O.R.S.E. (I...,Our HITMAN H.O.R.S.E. series returns with a TW...
1126,This solid is over 99% air,Silica aerogel is one of the world's lightest ...

In [7]:
y_train

244          Lifestyle
1101    Sports & Games
1265         Lifestyle
1244          Shopping
1253              News
             ...
1130       Video Games
1294    Sports & Games
860     Food & Cooking
1459       Video Games
1126         Education
Name: category, Length: 1480, dtype: object

In [ ]:
# Save train
X_train.to_csv(f"{TRAIN_DIR}/training_data.csv", index=False)
y_train.to_csv(f"{TRAIN_DIR}/training_labels.csv", index=False)

# Save validation
X_valid.to_csv(f"{TRAIN_DIR}/validation_data.csv", index=False)
y_valid.to_csv(f"{TRAIN_DIR}/validation_labels.csv", index=False)

# Save test (no labels exposed)
X_test.to_csv(f"{TRAIN_DIR}/test_data.csv", index=False)

# Save hidden test labels for scoring
y_test.to_csv(f"{REF_DIR}/test_labels.csv", index=False)

print("Codabench dataset created successfully.")

Codabench dataset created successfully.